[AMDGPU] Fix -Wpessimizing-move in AMDGPUSwLowerLDS.cpp (NFC)
/llvm-project/llvm/lib/Target/AMDGPU/AMDGPUSwLowerLDS.cpp:260:10:
error: moving a local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]
  return std::move(OrderedKernels);
         ^
/llvm-project/llvm/lib/Target/AMDGPU/AMDGPUSwLowerLDS.cpp:260:10: note: remove std::move call here
  return std::move(OrderedKernels);
         ^~~~~~~~~~              ~
1 error generated.

Change-Id: I240a5a9c29800eabb00c1264ef42959a674b5d56